name: 🐛 Bug Report
description: If something isn't working as expected 🤔.
labels:
  - bug
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: >
        Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: Yes, I have searched the existing issues
          required: true

  - type: textarea
    attributes:
      label: The problem
      description: >
        Provide a clear and concise description of what the problem is.

        Tell us what you were trying to do and what happened.
    validations:
      required: true

  - type: textarea
    attributes:
      label: The expected behavior
      description: >
        Describe what was expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Relevant code
      description: Please, provide an example of the code that doesn't work.
      render: ts

  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What is version of `@autoviews/core` are you using?
      placeholder: vX.X.X
      description: >
        Run `npm info @autoviews/core version` to get the version you are using.

  - type: input
    id: link
    attributes:
      label: Do you have a code demo link?
      placeholder: https://codesandbox.io/s/new
      description: >
        In order to resolve your issue quickly, please provide a link to a demo reproducing the problem.

        https://codesandbox.io/s/new

  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.

        Provide logs, suggestions, possible solutions, fixes or anything you consider useful.

        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
      render: markdown
