name: 🚀 Feature Request
description: I have a suggestion (and might want to implement myself 🙂)!
labels:
  - feature-request
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: >
        Please search to see if an issue already exists for the feature you are suggesting.
      options:
        - label: Yes, I have searched the existing issues
          required: true

  - type: textarea
    attributes:
      label: The problem
      description: >
        Is your feature request related to a problem? Please describe.
        Provide a clear and concise description of what the problem is.

        Tell us what you were trying to do and what happened.
      render: markdown

  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the solution you'd like
      description: >
        A clear and concise description of what you want to happen. Add any considered drawbacks.
      render: markdown

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: >
        A clear and concise description of any alternative solutions or features you've considered.
      render: markdown
